title: Bikram Dhoju
description: "Linux, security, DevOps stuff"

author:
  name: "Bikram Dhoju"
  email: "bikram.dhoju@gmail.com"
  url: "https://becram.github.io"

baseurl: ""
url: "https://becram.github.io"

source: .
destination: ./_site
permalink: /:title
paginate: 5
paginate_path: /page/:num/

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  hard_wrap: false

sass:
  sass_dir: _sass
  style: compressed

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

future: true

# Custom variables
owner: "Bikram Dhoju"
year: "2025"
github: "Becram"
twitter: "itsbecram"
linkedin: ""
